# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WT4lgOBnuhYYLU_piWS_M-HCnOhet2XH
"""

# Juego gamificado: Explorador de Decisiones
# Autor: Mirian + Copilot

def juego():
    print("🌍 Bienvenido/a al juego 'Explorador de Decisiones'")
    print("Responde las preguntas y descubrí tu perfil.\n")

    puntajes = {
        "Innovador": 0,
        "Estratégico": 0,
        "Colaborativo": 0,
        "Audaz": 0
    }

    # Pregunta 1
    print("1️⃣ El río caudaloso: Tenés que cruzar un río. ¿Qué hacés?")
    print("A) Construís una balsa improvisada")
    print("B) Buscás un puente más adelante")
    print("C) Pedís ayuda a otros viajeros")
    resp = input("Tu elección (A/B/C): ").upper()
    if resp == "A": puntajes["Innovador"] += 1
    elif resp == "B": puntajes["Estratégico"] += 1
    elif resp == "C": puntajes["Colaborativo"] += 1

    # Pregunta 2
    print("\n2️⃣ El camino oscuro: El sendero se divide en dos.")
    print("A) Elegís el iluminado (seguro)")
    print("B) Elegís el oscuro (riesgoso)")
    print("C) Esperás más información")
    resp = input("Tu elección (A/B/C): ").upper()
    if resp == "A": puntajes["Estratégico"] += 1
    elif resp == "B": puntajes["Audaz"] += 1
    elif resp == "C": puntajes["Estratégico"] += 1

    # Pregunta 3
    print("\n3️⃣ El cofre misterioso: Encontrás un cofre cerrado.")
    print("A) Intentás abrirlo con ingenio")
    print("B) Lo dejás y seguís")
    print("C) Lo marcás para volver después")
    resp = input("Tu elección (A/B/C): ").upper()
    if resp == "A": puntajes["Innovador"] += 1
    elif resp == "B": puntajes["Audaz"] += 1
    elif resp == "C": puntajes["Estratégico"] += 1

    # Pregunta 4
    print("\n4️⃣ El cruce final: Llegás a una montaña que bloquea tu paso.")
    print("A) Escalás directamente")
    print("B) Buscás un camino alternativo")
    print("C) Esperás ayuda externa")
    resp = input("Tu elección (A/B/C): ").upper()
    if resp == "A": puntajes["Audaz"] += 1
    elif resp == "B": puntajes["Estratégico"] += 1
    elif resp == "C": puntajes["Colaborativo"] += 1

    # Resultado final
    perfil = max(puntajes, key=puntajes.get)
    print("\n🎉 Tu perfil es:", perfil)
    if perfil == "Innovador":
        print("👉 Sos creativo/a y resolutivo/a, buscás soluciones originales.")
    elif perfil == "Estratégico":
        print("👉 Sos analítico/a y planificador/a, pensás en el largo plazo.")
    elif perfil == "Colaborativo":
        print("👉 Valorás el trabajo en equipo y la comunicación.")
    elif perfil == "Audaz":
        print("👉 Te adaptás rápido y tomás riesgos con confianza.")

juego()